# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20160502_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aconselhamento',
            name='sala',
            field=models.IntegerField(choices=[(1, 'sala 1'), (2, 'sala 2'), (3, 'sala 3'), (4, 'sala 4'), (5, 'sala 5')]),
        ),
        migrations.AlterField(
            model_name='membro',
            name='conjuge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_casamento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_conf',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='data_nasc',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='membro',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='membro',
            name='mae',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='membro',
            name='origem',
            field=models.CharField(blank=True, choices=[('cursilho', 'cursilho'), ('lado', 'lado a lado'), ('discipulado', 'discipulado'), ('transf', 'transf outra comunidade'), ('olimp', 'olimpiadas'), ('outros', 'outros')], max_length=6),
        ),
        migrations.AlterField(
            model_name='membro',
            name='pai',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='membro',
            name='profissao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='membro',
            name='sexo',
            field=models.CharField(blank=True, choices=[('mas', 'masculino'), ('fem', 'feminino'), ('out', 'outro')], max_length=3),
        ),
    ]
