# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20160528_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertence_ministerio',
            name='funcao',
            field=models.IntegerField(choices=[(1, 'fez'), (2, 'trabalha'), (3, 'lidera')]),
        ),
    ]
