# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_auto_20160528_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertence_ministerio',
            name='ministerio',
            field=models.IntegerField(choices=[(1, 'Cursilho'), (2, 'Mentoria de casais'), (3, 'Discipulado'), (4, 'Seminário de vida'), (5, 'Olimpíadas')]),
        ),
    ]
