# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_membro_escolaridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='peridiocidade',
            field=models.CharField(blank=True, choices=[('uma', 'uma vez'), ('semanalmente', 'semanalmente'), ('quinzenal', 'quizenal'), ('mensal', 'mensal')], max_length=5),
        ),
    ]
