# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_evento_peridiocidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='secretario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretario', to='crud.Secretario'),
        ),
    ]
