# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_auto_20160529_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, choices=[('canaa', 'Canaã'), ('betania', 'Catedral Betânia'), ('outros', 'Outros')], max_length=5),
        ),
    ]
